import ActivitiesDatagridCellActions from "../../common/activities-datagrid-cell-actions";

export const dummyData = [
  {
    id: 1,
    type: "City Tour",
    name: "Yerevan center",
    address: "test address 1",
    contactName: "Person 1",
    email: "whatisyouremail@test.com",
    phone: "+11223344",
    website: "besttestwebsite.com",
    price: "1000 AMD",
  },
  {
    id: 2,
    type: "Resturant",
    name: "Shereq",
    address: "address ",
    contactName: "Person 2",
    email: "whatisyouremail@test.com",
    phone: "+4545656",
    website: "besttestwebsite.com",
    price: "10000 AMD",
  },
  {
    id: 3,
    type: "Resturant",
    name: "Ankyun",
    address: "test address 3",
    contactName: "Person 3",
    email: "whatisyouremail@test.com",
    phone: "+22333",
    website: "besttestwebsite.com",
    price: "3333 AMD",
  },
  {
    id: 4,
    type: "Test Type",
    name: "Test Type Name",
    address: "test address 1",
    contactName: "Person 4",
    email: "whatisyouremail@test.com",
    phone: "+667788",
    website: "besttestwebsite.com",
    price: "2222 AMD",
  },
  {
    id: 5,
    type: "Test data2",
    name: "Yerevan small",
    address: "test address 1",
    contactName: "Person 1",
    email: "whatisyouremail@test.com",
    phone: "+11223344",
    website: "besttestwebsite.com",
    price: "1000 AMD",
    changeUser: 11,
  },
  {
    id: 6,
    type: "Tasting",
    name: "Yerevan Brandy Factory",
    address: "Yerevan address 1",
    contactName: "Poghos Poghosyan",
    email: "poghospoghosyan@test.com",
    phone: "+11223344",
    website: "poghospoghosyan.com",
    price: "5555 AMD",
  },
  {
    id: 7,
    type: "Historical",
    name: "Garni Tample",
    address: "Garni village",
    contactName: "Artur Petrosyan ",
    email: "whatisyouremail@test.com",
    phone: "+11223344",
    website: "besttestwebsite.com",
    price: "1000 AMD",
  },
  {
    id: 8,
    type: "Extreme",
    name: "Yell Park",
    address: "Amiryan str. 1",
    contactName: "Armine Petrosyan",
    email: "armine@test.com",
    phone: "+11223344",
    website: "besttestwebsite.com",
    price: "6753 AMD",
  },
  {
    id: 9,
    type: "Church",
    name: "Ayrivank",
    address: "Ankap Chol 4/3",
    contactName: "Person 1",
    email: "whatisyouremail@test.com",
    phone: "+11223344",
    website: "besttestwebsite.com",
    price: "N/A",
  },
  {
    id: 10,
    type: "Hiking",
    name: "Dilijan",
    address: "Dilijan",
    contactName: "Name Name",
    email: "whatisyouremail@test.com",
    phone: "+11223344",
    website: "namename.com",
    price: "1500 AMD",
  },
  {
    id: 11,
    type: "City Tour",
    name: "Gyumri",
    address: "Lennagan!!!!",
    contactName: "Tso inch x te",
    email: "tsoinchxte@test.com",
    phone: "+11223344",
    website: "besttestwebsite.com",
    price: "25000 AMD",
  },
  {
    id: 12,
    type: "City Tour",
    name: "Yerevan small center",
    address: "test address 1",
    contactName: "Person 1",
    email: "whatisyouremail@test.com",
    phone: "+11223344",
    website: "besttestwebsite.com",
    price: "5555 AMD",
  },
  {
    id: 13,
    type: "City Tour",
    name: "Yerevan small center",
    address: "test address 1",
    contactName: "Person 1",
    email: "whatisyouremail@test.com",
    phone: "+11223344",
    website: "besttestwebsite.com",
    price: "43432 AMD",
  },
];

export const columns = [
  {
    field: "type",
    headerName: "Type",
    flex: 0.25,
    renderCell: ({ value: { activityName } }) => activityName,
  },
  {
    field: "name",
    headerName: "Name",
    flex: 0.25,
  },
  {
    field: "address",
    headerName: "Address",
    flex: 0.25,
  },
  {
    field: "contactName",
    headerName: "Contact Name",
    flex: 0.25,
  },
  {
    field: "email",
    headerName: "Email",
    flex: 0.4,
  },
  {
    field: "phone",
    headerName: "Phone",
    flex: 0.2,
  },
  {
    field: "website",
    headerName: "Website",
    flex: 0.3,
  },
  {
    field: "price",
    headerName: "Price",
  },
  {
    field: "actions",
    headerName: "Actions",
    width: 150,
    renderCell: ActivitiesDatagridCellActions,
  },
];
