trigger:
  - devops

variables:
  imageTag: $(Build.BuildId)
  containerRepository: travely/front
  containerRegistry: registry-travely-am
  containerRegistryHost: registry.travely.am

stages:
# Build stage
- template: templates/build.yml
  parameters:
    imageTag: $(imageTag)
    containerRepository: $(containerRepository)
    containerRegistry: $(containerRegistry)
# Deploy stage
- template: templates/deploy.yml
  parameters:
    imageTag: $(containerRegistryHost)/$(imageTag)
    containerRepository: $(containerRepository)
    containerRegistry: $(containerRegistry)
    containerRegistryPassword: $(registry_travely_am_password)
    containerPort: 5000
    hostname: front.travely.am
    path: /
    cname: k8s.travely.am
    environment: dev.dev-travely-am
    kubernetesServiceConnection: dev-dev-travely-am-1639235401610
    kubernetesNamespace: dev-travely-am
    ingress:
      enabled: true
    helmMetadata:
      releaseName: front
      chartRegistry: $(containerRegistryHost)
