trigger:
  - devops

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      displayName: "Build and push to docker hub with latest tag."
      inputs:
        containerRegistry: "registry.travely.am"
        repository: "travely/front"
        command: "buildAndPush"
        Dockerfile: "Dockerfile"
        buildContext: "."
        tags: |
          $(Build.BuildId)
          latest
- stage: Deploy
  jobs:
  - deployment: Deploy
    environment: dev.dev-travely-am
    variables:
    - name: HELM_EXPERIMENTAL_OCI
      value: 1
    strategy:
      runOnce:
        deploy:
          steps:
            - script: "helm registry login registry.travely.am -u admin -p $(registry_travely_am_password) && helm pull oci://registry.travely.am/helm-charts/app --version 0.1.0"
            - task: KubernetesManifest@0
              name: bake
              inputs:
                action: bake
                renderType: helm
                helmChart: "app-0.1.0.tgz"
                overrides: |
                  image.repository:travely/front
                  image.tag:$(Build.BuildId)
                  ingress.enabled:false
                  fullnameOverride:travely-front-dev
                  serviceAccount.create:false
            - task: KubernetesManifest@0
              name: deploy
              inputs:
                action: 'deploy'
                kubernetesServiceConnection: 'dev-dev-travely-am-1637185039689'
                namespace: 'dev-travely-am'
                manifests: $(bake.manifestsBundle)
