trigger:
  - devops

resources:
  repositories:
    - repository: travely
      type: github
      name: titancamp/travely

variables:
  imageTag: $(Build.BuildId)
  containerRepository: travely/front
  containerRegistry: registry-travely-am
  containerRegistryHost: registry.travely.am

stages:
# Build stage
- template: templates/build.yml@travely
  parameters:
    imageTag: $(imageTag)
    containerRepository: $(containerRepository)
    containerRegistry: $(containerRegistry)
# Deploy stage
- template: templates/deploy.yml@travely
  parameters:
    imageTag: $(imageTag)
    containerRepository: $(containerRegistryHost)/$(containerRepository)
    containerRegistry: $(containerRegistry)
    containerRegistryPassword: $(registry_travely_am_password)
    containerPort: 5000
    hostname: front.travely.am
    path: /
    cname: k8s.travely.am
    environment: dev.dev-travely-am
    kubernetesServiceConnection: dev-dev-travely-am-1639235401610
    kubernetesNamespace: dev-travely-am
    ingress:
      enabled: true
    helmMetadata:
      releaseName: front
      chartRegistry: $(containerRegistryHost)
      chartName: helm-charts/app
      chartVersion: 0.1.1
