trigger:
- master

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'travely-client'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    buildContext: '.'
    tags: 'travely-client-$(Build.BuildId)'
  