trigger:
- master

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'titancamp\travely-client'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    buildContext: '.'