trigger:
- master

steps:
- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: 'Dockerfile'
    buildContext: '.'
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'travely-client'
    command: 'push'