trigger:
  branches:
    include:
    - dev
pr:
  branches:
    include:
    - dev

resources:
  repositories:
  - repository: travely
    type: github
    name: titancamp/travely
    ref: refs/heads/develop
    endpoint: k-harutyunyan
    
variables:
- group: travely-dev
- name: project
  value: front
- name: gitBranch
  value: $(Build.SourceBranchName)
- name: imageTag
  value: $(Build.BuildId)
- name: containerRepository
  value: travely/$(project)/$(gitBranch)
- name: containerRegistry
  value: registry-travely-am
- name: containerRegistryHost
  value: registry.travely.am

stages:
# Build stage
- template: .devops/templates/build.yml@travely
  parameters:
    imageTag: $(imageTag)
    containerRepository: $(containerRepository)
    containerRegistry: $(containerRegistry)
# Deploy stage
- ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
  - template: .devops/templates/deploy.yml@travely
    parameters:
      imageTag: $(imageTag)
      containerRepository: $(containerRegistryHost)/$(containerRepository)
      containerRegistry: $(containerRegistry)
      containerRegistryPassword: $(registry_travely_am_password)
      containerPort: 5000
      hostname: dev.travely.am
      path: /
      cname: k8s.travely.am
      environment: dev.dev-travely-am
      kubernetesServiceConnection: dev-dev-travely-am-1639235401610
      kubernetesNamespace: dev-travely-am
      ingress:
        enabled: true
      helmMetadata:
        releaseName: $(project)
        chartRegistry: $(containerRegistryHost)
        chartName: helm-charts/app
        chartVersion: 0.1.2
