trigger:
  - dev

resources:
  repositories:
  - repository: travely
    type: github
    name: titancamp/travely
    ref: refs/heads/develop
    endpoint: k-harutyunyan

variables:
  imageTag: $(Build.BuildId)
  containerRepository: travely/front
  containerRegistry: registry-travely-am
  containerRegistryHost: registry.travely.am

stages:
# Build stage
- template: .devops/templates/build.yml@travely
  parameters:
    imageTag: $(imageTag)
    containerRepository: $(containerRepository)
    containerRegistry: $(containerRegistry)
# Deploy stage
- template: .devops/templates/deploy.yml@travely
  parameters:
    imageTag: $(imageTag)
    containerRepository: $(containerRegistryHost)/$(containerRepository)
    containerRegistry: $(containerRegistry)
    containerRegistryPassword: $(registry_travely_am_password)
    containerPort: 5000
    hostname: dev.travely.am
    path: /
    cname: k8s.travely.am
    environment: dev.dev-travely-am
    kubernetesServiceConnection: dev-dev-travely-am-1639235401610
    kubernetesNamespace: dev-travely-am
    containerEnv:
    - name: n1
      value: v1
    - name: n2
      value: v2
    - name: n3
      value: v3
    - name: n4
      value: v4
    ingress:
      enabled: true
    helmMetadata:
      releaseName: front
      chartRegistry: $(containerRegistryHost)
      chartName: helm-charts/app
      chartVersion: 0.1.2
