export default (() => ({
  Accomodation: [
    {
      id: 1,
      name: 'Dilijan Resort',
      roomType: 'Single Room',
      count: 2,
      days: 14,
      currency: 'AMD',
      costPerDay: 33000,
      totalCost: 924000,
    },
    {
      id: 2,
      name: 'Dilijan Resort',
      roomType: 'Double Room',
      count: 3,
      days: 7,
      currency: 'AMD',
      costPerDay: 40000,
      totalCost: 840000,
    },
    {
      id: 3,
      name: 'Tsakhkadzor Resort',
      roomType: 'Double Room',
      count: 3,
      days: 7,
      currency: 'AMD',
      costPerDay: 45000,
      totalCost: 945000,
    },
  ],
  Transportation: [
    {
      id: 1,
      name: 'Transportation Agency 1',
      priceType: 'Flat',
      distance: '100km',
      pricePerKm: 55,
      amount: 0,
      days: 7,
      currency: 'AMD',
      costPerDay: 25000,
      totalCost: 175000,
    },
    {
      id: 2,
      name: 'Transportation Agency 2',
      priceType: 'Km',
      distance: '100km',
      pricePerKm: 55,
      amount: 5500,
      days: 7,
      currency: 'AMD',
      costPerDay: 0,
      totalCost: 38500,
    },
  ],
  Food: [
    {
      id: 1,
      name: 'Restaurant Name',
      priceType: 'Flat',
      guests: 5,
      currency: 'AMD',
      costPerGuest: 15000,
      totalCost: 75000,
    },
  ],
  Guide: [
    {
      id: 1,
      name: 'Guide Name',
      priceType: 'Flat',
      days: 7,
      currency: 'AMD',
      costPerDay: 30000,
      totalCost: 210000,
    },
  ],
  Activity: [
    {
      id: 1,
      name: 'Activity Name 1',
      priceType: 'Flat',
      guests: 5,
      currency: 'AMD',
      costPerGuest: 10000,
      totalCost: 50000,
    },
  ],
}))();
