export const TOUR_COLUMNS = [
  { field: "status", headerName: "Status" },
  { field: "name", headerName: "Name", width: 150 },
  { field: "origin", headerName: "Origin" },
  { field: "days", headerName: "Nr. of days" },
  { field: "destination", headerName: "Destination", width: 150 },
  { field: "date", headerName: "Dates", width: 150 },
  { field: "guests", headerName: "Guests", width: 150 },
  { field: "hotels", headerName: "Hotels", width: 150 },
  { field: "activities", headerName: "Activities", width: 150 },
  { field: "flight", headerName: "Flight" },
  { field: "price", headerName: "Price" },
  { field: "notes", headerName: "Notes" },
  { field: "createdBy", headerName: "Created By" },
];

export const TOUR_ROWS = [
  {
    id: 1,
    status: "All booked",
    name: "Bellinis in Armenia",
    origin: "Italy",
    days: "7",
    date: "Jan 28-Feb 11",
    destination: "Yerevan, Sevan, Dilijan",
    guests: "Marco Belini, Chiara Belini",
    hotels: "Noy Land, Popock 1",
    activities: "Yell Park, Papanino",
    flight: "QR 706",
    price: "$5400",
    notes: "Very picky person",
    createdBy: "Armine G",
  },
  {
    id: 2,
    status: "All booked",
    name: "Bellinis in Armenia",
    origin: "Italy",
    days: "7",
    date: "Jan 28-Feb 11",
    destination: "Yerevan, Sevan, Dilijan",
    guests: "Marco Belini, Chiara Belini",
    hotels: "Noy Land, Popock 1",
    activities: "Yell Park, Papanino",
    flight: "QR 706",
    price: "$5400",
    notes: "Very picky person",
    createdBy: "Armine G",
  },
];

export const GUESTS_COLUMNS = [
  { field: "firstName", headerName: "First name" },
  { field: "lastName", headerName: "Last name" },
  { field: "phone", headerName: "Phone" },
  { field: "email", headerName: "Email" },
  { field: "dateOfBirth", headerName: "Date of birth" },
  { field: "placeOfBirth", headerName: "Place of birth" },
  { field: "passport", headerName: "Passport" },
  { field: "issuedBy", headerName: "Issued by" },
  { field: "issueDate", headerName: "Issue date" },
  { field: "expireDate", headerName: "Expire date" },
  { field: "notes", headerName: "Notes" },
];

export const GUESTS_ROWS = [
  {
    id: 1,
    firstName: "Artur",
    lastName: "Vahanyan",
    phone: "099009800",
    email: "artur.va@gmail.com",
    dateOfBirth: "Jan 28-Feb 11",
    placeOfBirth: "Chishineu",
    passportNumber: "AN23478326",
    issuedBy: "004",
    issueDate: "02.02.16",
    expirationDate: "02.02.26",
    notes: "ababscjfbwjsvc",
  },
  {
    id: 2,
    firstName: "Valod",
    lastName: "Hakobyan",
    phone: "0990098001",
    email: "artur.va@gmail.com1",
    dateOfBirth: "Jan 28-Feb 12",
    placeOfBirth: "Chishineu1",
    passportNumber: "AN234783261",
    issuedBy: "0044",
    issueDate: "02.02.15",
    expirationDate: "02.02.25",
    notes: "ascasc",
  },
];
